# Question 1

In [16]:
import numpy as np 
import pandas as pd

In [17]:
import numpy as geek 

In [18]:
aray=geek.array([1,2,3,4,5])

In [20]:
vander_aray=geek.vander(aray)

In [21]:
print(vander_aray)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# Question 2

In [23]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

a = np.arange(10,100,10) #checking moving average
N=3
moving_average(a,N)

array([20., 30., 40., 50., 60., 70., 80.])

In [26]:
a1= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N=3
moving_average(a1,N).round(1)

array([  5. ,   4.7,   5.7,   6.7,   9.7,  28.7,  49.3,  72.7,  84. ,
        93.3, 116.3])